
services:
  redis-stack:
    image: redis/redis-stack:latest
    volumes:
      - redis-stack-data:/bitnami/redis/data
    hostname: redis1
    ports:
      - "8001:8001"
      - "6379:6379"
    networks:
      - redisnet

volumes:
  redis-stack-data:

networks:
  redisnet: { }